const tr = {
        nav: {
            nasil: 'Nasıl çalışır',
            pasaport: 'Pasaport',
            urunler: 'Ürünler',
            dunya: 'Dünya',
            giris: 'Giriş Yap',
            basla: 'Ücretsiz Başla',
        },
        hero: {
            eyebrow: 'Menşe doğrulama, blockchain’de',
            satir1: 'Ürün Dünyayı Dolaşır,',
            satir2: 'Menşei Onunla',
            satir3: 'Gelir.',
            aciklama: 'Coğrafi işaretli ürünler için blockchain izlenebilirlik. Kaydedin, QR’ı ürüne ekleyin, dünyanın her yerinde doğrulatın.',
            link: 'Nasıl çalışır',
        },
        tez: {
            eyebrow: 'Sorun',
            satirlar: [
                'Bir kavanoz Anzer balı Riyad’daki rafa ulaştığında,',
                'etiketinde yazan her şey bir iddiadır.',
                'Sınırı geçen şey kutu değil, kayıt olmalı.',
            ],
        },
        yolculuk: {
            eyebrow: 'Nasıl çalışır',
            baslik: 'Tarladan rafa, her adım bir blok.',
            aciklama: 'Üretici ürünü ekler, OriginTag kaydı özetleyip Polygon ağına yazar, ürüne bir QR verir. Müşteri dünyanın neresinde olursa olsun taratır ve aynı kaydı görür — değiştirilmemiş, tarihli, imzalı.',
            adimlar: [
                {
                    anahtar: 'kayit',
                    baslik: 'Üretici kaydeder',
                    metin: 'Ürün adı, bölge, hasat tarihi, miktar, fotoğraf ve video. Teknik bilgi gerekmez; bir form, iki dakika.',
                    defter: 'urun_adi · bolge · hasat_tarihi · medya',
                    video: '/videos/landing-hero.mp4',
                },
                {
                    anahtar: 'zincir',
                    baslik: 'Zincire yazılır',
                    metin: 'Kayıt SHA-256 ile özetlenir ve Polygon ağına yazılır. Bu satır bir daha silinemez, değiştirilemez.',
                    defter: 'hash = 0x9da4…387a  ·  tx = polygon/amoy',
                    video: '/videos/bal-hero.mp4',
                },
                {
                    anahtar: 'qr',
                    baslik: 'QR ürüne biner',
                    metin: 'Her ürün için tek, kopyalanamaz bir QR. Etikete, kutuya, tenekeye — ürün nereye giderse kayıt da oraya gider.',
                    defter: 'origintag.com.tr/dogrula/{hash}',
                    video: '/videos/zeytinyagi-hero.mp4',
                },
                {
                    anahtar: 'tarama',
                    baslik: 'Müşteri taratır',
                    metin: 'Berlin’de, Dubai’de, Tokyo’da. Telefon kamerası yeter: ürünün pasaportu açılır, kaynak köy görünür.',
                    defter: 'dogrulama = ✓  ·  kayit_tarihi eşleşti',
                    video: '/videos/bugday-hero.mp4',
                },
            ],
        },
        pasaport: {
            eyebrow: 'Ürün pasaportu',
            baslik1: 'Müşterinin gördüğü',
            baslik2: 'tam olarak bu.',
            aciklama: 'QR tarandığında açılan sayfa: hasat, kayıt ve doğrulama tarihleri, blockchain özeti, üretici ve bölge bilgisi. Aşağıda deneyin.',
            tarat: 'Tarat',
            taraniyor: 'Doğrulanıyor…',
            dogrulandi: 'Blockchain doğrulandı',
            yeniden: 'Yeniden tarat',
            not: 'Örnek pasaport. Gerçek kayıtlar /dogrula altında açılır.',
            urun: {
                bolge: 'Ayvalık, Balıkesir',
                ad: 'Erken Hasat Zeytinyağı',
                tip: 'Zeytinyağı · Coğrafi işaretli',
            },
            adimlar: [
                { etiket: 'Hasat', tarih: '14.10.2025' },
                { etiket: 'Blockchain Kaydı', tarih: '16.10.2025' },
                { etiket: 'Bu Doğrulama', tarih: 'Bugün', aktif: true },
            ],
            alanlar: [
                { k: 'Üretici', v: 'Taşeli Zeytincilik' },
                { k: 'Ürün tipi', v: 'Natürel sızma' },
                { k: 'Miktar', v: '5 L' },
                { k: 'Kayıt', v: 'Polygon · Amoy' },
            ],
            hashEtiket: 'Blockchain özeti',
            hash: '0x9da4f1c2a7e0b38b5c6d2e9f47a1c0d3e5b8f2a6c4d1e7b9f0a3c5d8e2b4f6a1',
        },
        kategoriler: {
            eyebrow: 'Ürünler',
            baslik: 'Coğrafi işareti olan her şey için.',
            aciklama: 'Türkiye’de 1.500’den fazla tescilli coğrafi işaret var. Her biri bir yerin adını taşıyor; OriginTag o adı ürünün üstünde tutar.',
            liste: [
                { ad: 'Zeytinyağı', ornek: 'Ayvalık · Mut · Edremit' },
                { ad: 'Bal', ornek: 'Anzer · Kars · Muğla' },
                { ad: 'Peynir', ornek: 'Ezine · Erzincan Tulum · Kars Gravyer' },
                { ad: 'Süt Ürünleri', ornek: 'Afyon Kaymağı · Bingöl Tereyağı' },
                { ad: 'Kahve', ornek: 'Menengiç · Dibek' },
                { ad: 'Sebze & Meyve', ornek: 'Malatya Kayısısı · Antep Fıstığı · Finike Portakalı' },
                { ad: 'Tahıl', ornek: 'Kars Kavılcası · Siyez Bulguru' },
                { ad: 'Şarap', ornek: 'Kalecik Karası · Öküzgözü' },
                { ad: 'Turşu & Reçel', ornek: 'Çubuk Turşusu · Bursa Kestane Şekeri' },
            ],
        },
        kanit: {
            eyebrow: 'Neden OriginTag',
            baslik: 'Şeffaflık, kanıtla birlikte gelir.',
            maddeler: [
                { baslik: 'Değiştirilemez kayıt', metin: 'Kayıt SHA-256 ile özetlenir ve Polygon ağına yazılır. Geriye dönüp düzeltmek mümkün değildir — üretici için de, OriginTag için de.' },
                { baslik: 'Menşe kanıtı', metin: 'Bölge, köy, hasat tarihi ve fotoğraf tek bir kayıtta. Taklit ürün, gerçek kaydı gösteremez.' },
                { baslik: 'Tek QR, her yer', metin: 'Uygulama indirmek gerekmez. Telefon kamerası kayıt sayfasını açar; sayfa Türkçe ve İngilizce.' },
                { baslik: 'Sürdürülebilirlik profili', metin: 'Üretici sertifika, sulama, kimyasal girdi ve enerji beyanını ekler; kural tabanlı bir skor pasaportta görünür.' },
                { baslik: 'İhracata hazır', metin: 'Coğrafi işaret belgesiyle uyumlu yapı. AB ve uluslararası alıcılar kaynağı kendi gözleriyle doğrular.' },
                { baslik: 'İki dakikada kurulum', metin: 'Kayıt olun, ürünü ekleyin, QR’ı indirin. Teknik bilgi, cüzdan ya da kripto gerekmez.' },
            ],
        },
        dunya: {
            eyebrow: 'Dünyaya açılın',
            baslik: 'Türkiye’den dünya raflarına, kayıt yanında.',
            aciklama: 'Coğrafi işaret belgeli ürünleriniz, blockchain kaydıyla birlikte uluslararası pazarlarda güvenilirlik kazanır. Küreyi sürükleyin; rotalar üreticiden alıcıya uzanır.',
            ipucu: 'Sürükleyerek çevirin',
        },
        memories: {
            eyebrow: 'Aynı altyapı, başka bir yolculuk',
            baslik: 'OriginTag Memories',
            aciklama: 'Ürünler için kurduğumuz pasaport altyapısı, oteller için dijital seyahat pasaportuna dönüşüyor: misafir bir QR ile konaklamasını, rotasını ve anılarını tek sayfada taşır.',
            link: 'Demo pasaportu gör',
        },
        kapanis: {
            baslik1: 'Hikayeniz',
            baslik2: 'yola çıkmaya hazır.',
            aciklama: 'Ücretsiz hesap, ilk ürün, ilk QR — bugün.',
            cta: 'Ücretsiz Başla',
            ctaIkincil: 'Bir ürün doğrula',
        },
        footer: {
            slogan: 'Coğrafi işaret & izlenebilirlik',
            baglantilar: [
                { etiket: 'Giriş Yap', href: '/login' },
                { etiket: 'Kayıt Ol', href: '/register' },
                { etiket: 'Ürün Doğrula', href: '/dogrula' },
                { etiket: 'Gizlilik', href: '/gizlilik' },
            ],
            telif: '© 2026 OriginTag',
        },
};

export type LandingIcerik = typeof tr;

const en: LandingIcerik = {
        nav: {
            nasil: 'How it works',
            pasaport: 'Passport',
            urunler: 'Products',
            dunya: 'World',
            giris: 'Sign In',
            basla: 'Get Started Free',
        },
        hero: {
            eyebrow: 'Origin verification, on-chain',
            satir1: 'The Product Travels,',
            satir2: 'Its Origin Travels',
            satir3: 'With It.',
            aciklama: 'Blockchain traceability for geographically indicated products. Record it, put the QR on the product, verify it anywhere in the world.',
            link: 'How it works',
        },
        tez: {
            eyebrow: 'The problem',
            satirlar: [
                'When a jar of Anzer honey reaches a shelf in Riyadh,',
                'everything on its label is a claim.',
                'What crosses the border should be a record, not a box.',
            ],
        },
        yolculuk: {
            eyebrow: 'How it works',
            baslik: 'From field to shelf, every step is a block.',
            aciklama: 'The producer adds the product, OriginTag hashes the record and writes it to Polygon, then issues a QR. Wherever the customer is, they scan and see the same record — unaltered, dated, signed.',
            adimlar: [
                { anahtar: 'kayit', baslik: 'The producer records', metin: 'Product name, region, harvest date, amount, photos and video. No technical knowledge; one form, two minutes.', defter: 'product · region · harvest_date · media', video: '/videos/landing-hero.mp4' },
                { anahtar: 'zincir', baslik: 'Written on-chain', metin: 'The record is hashed with SHA-256 and written to the Polygon network. That line can never be deleted or edited.', defter: 'hash = 0x9da4…387a  ·  tx = polygon/amoy', video: '/videos/bal-hero.mp4' },
                { anahtar: 'qr', baslik: 'The QR rides along', metin: 'One uncopyable QR per product. On the label, the box, the tin — wherever the product goes, the record follows.', defter: 'origintag.com.tr/dogrula/{hash}', video: '/videos/zeytinyagi-hero.mp4' },
                { anahtar: 'tarama', baslik: 'The customer scans', metin: 'In Berlin, Dubai, Tokyo. A phone camera is enough: the passport opens, the source village appears.', defter: 'verified = ✓  ·  record_date matched', video: '/videos/bugday-hero.mp4' },
            ],
        },
        pasaport: {
            eyebrow: 'Product passport',
            baslik1: 'What the customer sees',
            baslik2: 'is exactly this.',
            aciklama: 'The page that opens when the QR is scanned: harvest, record and verification dates, the blockchain digest, producer and region. Try it below.',
            tarat: 'Scan',
            taraniyor: 'Verifying…',
            dogrulandi: 'Blockchain verified',
            yeniden: 'Scan again',
            not: 'Sample passport. Real records open under /dogrula.',
            urun: { bolge: 'Ayvalık, Balıkesir', ad: 'Early Harvest Olive Oil', tip: 'Olive oil · Geographically indicated' },
            adimlar: [
                { etiket: 'Harvest', tarih: '14.10.2025' },
                { etiket: 'Blockchain Record', tarih: '16.10.2025' },
                { etiket: 'This Verification', tarih: 'Today', aktif: true },
            ],
            alanlar: [
                { k: 'Producer', v: 'Taşeli Zeytincilik' },
                { k: 'Product type', v: 'Extra virgin' },
                { k: 'Amount', v: '5 L' },
                { k: 'Ledger', v: 'Polygon · Amoy' },
            ],
            hashEtiket: 'Blockchain digest',
            hash: '0x9da4f1c2a7e0b38b5c6d2e9f47a1c0d3e5b8f2a6c4d1e7b9f0a3c5d8e2b4f6a1',
        },
        kategoriler: {
            eyebrow: 'Products',
            baslik: 'For anything with a geographical indication.',
            aciklama: 'Türkiye has more than 1,500 registered geographical indications. Each carries the name of a place; OriginTag keeps that name on the product.',
            liste: [
                { ad: 'Olive Oil', ornek: 'Ayvalık · Mut · Edremit' },
                { ad: 'Honey', ornek: 'Anzer · Kars · Muğla' },
                { ad: 'Cheese', ornek: 'Ezine · Erzincan Tulum · Kars Gruyère' },
                { ad: 'Dairy', ornek: 'Afyon Clotted Cream · Bingöl Butter' },
                { ad: 'Coffee', ornek: 'Menengiç · Dibek' },
                { ad: 'Fruit & Vegetables', ornek: 'Malatya Apricot · Antep Pistachio · Finike Orange' },
                { ad: 'Grain', ornek: 'Kars Kavılca · Siyez Bulgur' },
                { ad: 'Wine', ornek: 'Kalecik Karası · Öküzgözü' },
                { ad: 'Pickles & Jam', ornek: 'Çubuk Pickles · Bursa Candied Chestnut' },
            ],
        },
        kanit: {
            eyebrow: 'Why OriginTag',
            baslik: 'Transparency, backed by proof.',
            maddeler: [
                { baslik: 'Immutable record', metin: 'The record is hashed with SHA-256 and written to Polygon. Going back to fix it is impossible — for the producer and for OriginTag alike.' },
                { baslik: 'Proof of origin', metin: 'Region, village, harvest date and photos in one record. A counterfeit cannot show the real record.' },
                { baslik: 'One QR, anywhere', metin: 'No app to install. The phone camera opens the record page, in Turkish and English.' },
                { baslik: 'Sustainability profile', metin: 'The producer declares certification, irrigation, chemical inputs and energy; a rule-based score appears on the passport.' },
                { baslik: 'Export ready', metin: 'Aligned with geographical indication documentation. EU and international buyers verify the source themselves.' },
                { baslik: 'Two-minute setup', metin: 'Register, add the product, download the QR. No technical knowledge, wallet or crypto required.' },
            ],
        },
        dunya: {
            eyebrow: 'Reach the world',
            baslik: 'From Türkiye to shelves worldwide, record included.',
            aciklama: 'Your geographically indicated products gain international trust, backed by a blockchain record. Drag the globe; routes run from producer to buyer.',
            ipucu: 'Drag to rotate',
        },
        memories: {
            eyebrow: 'Same infrastructure, another journey',
            baslik: 'OriginTag Memories',
            aciklama: 'The passport infrastructure we built for products becomes a digital travel passport for hotels: a guest carries their stay, route and memories on one page, with one QR.',
            link: 'See the demo passport',
        },
        kapanis: {
            baslik1: 'Your story',
            baslik2: 'is ready to travel.',
            aciklama: 'Free account, first product, first QR — today.',
            cta: 'Get Started Free',
            ctaIkincil: 'Verify a product',
        },
        footer: {
            slogan: 'Geographical indication & traceability',
            baglantilar: [
                { etiket: 'Sign In', href: '/login' },
                { etiket: 'Register', href: '/register' },
                { etiket: 'Verify Product', href: '/dogrula' },
                { etiket: 'Privacy', href: '/gizlilik' },
            ],
            telif: '© 2026 OriginTag',
        },
};

export const ICERIK: Record<'tr' | 'en', LandingIcerik> = { tr, en };
